// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef app_h
#define app_h
#include <FL/Fl.H>
extern "C" { void error_for_exit(char *str); }
void set_user_connection(int port, int ipv6port);
int projector_start();
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win_main;
#include <FL/Fl_Light_Button.H>
extern Fl_Light_Button *share_button;
#include <FL/Fl_Text_Display.H>
extern Fl_Text_Display *log_window;
#include <FL/Fl_Button.H>
extern Fl_Button *log_button;
Fl_Double_Window* init_gui();
extern unsigned char logo_data[6992];
extern "C" { void write_log(const char *fmt, ...); }
#endif
